# Day 6 – Data Analysis with NumPy and Pandas

Complete notebook covering NumPy, Broadcasting, Pandas, Reading Files, Filtering, GroupBy, Missing Values, Data Preprocessing, Feature Engineering, and a Mini Project.

## NumPy Arrays

In [1]:
# numpy is a powerful library for numerical computing in Python. 
# It provides support for large multi-dimensional arrays and matrices, 
# along with a collection of mathematical functions to operate on these arrays.
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)

matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data Type:", matrix.dtype)

print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.arange(1,11))
print(np.linspace(0,1,5))

[10 20 30 40 50]
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 1  2  3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]


## Broadcasting

In [2]:
#Filtering means selecting only required rows
import numpy as np

arr = np.array([10,20,30])
print(arr + 5)

a = np.array([1,2,3])
b = np.array([10,20,30])
print(a + b)

matrix = np.array([[1,2,3],[4,5,6]])
row = np.array([10,20,30])
print(matrix + row)

[15 25 35]
[11 22 33]
[[11 22 33]
 [14 25 36]]


## Pandas DataFrame

In [3]:
#Pandas is the most important library for data analysis.
import pandas as pd

data = {
    "Name":["Tarun","Rahul","Priya"],
    "Age":[23,25,22],
    "Salary":[50000,60000,55000]
}

df = pd.DataFrame(data)
print(df)
print(df.info())
print(df.describe())

    Name  Age  Salary
0  Tarun   23   50000
1  Rahul   25   60000
2  Priya   22   55000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   Salary  3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None
             Age   Salary
count   3.000000      3.0
mean   23.333333  55000.0
std     1.527525   5000.0
min    22.000000  50000.0
25%    22.500000  52500.0
50%    23.000000  55000.0
75%    24.000000  57500.0
max    25.000000  60000.0


## Reading CSV Excel JSON

In [4]:
import pandas as pd

# Examples
# df = pd.read_csv("employees.csv")
# df = pd.read_excel("employees.xlsx")
# df = pd.read_json("employees.json")

print("Use read_csv, read_excel and read_json for external files.")

Use read_csv, read_excel and read_json for external files.


## Filtering Data

In [5]:
#Filtering means selecting only required rows.
import pandas as pd

df = pd.DataFrame({
    "Name":["A","B","C","D"],
    "Age":[20,25,30,35]
})

print(df[df["Age"] > 25])

result = df[(df["Age"] > 20) & (df["Age"] < 35)]
print(result)

print(df[df["Name"].isin(["A","C"])])

  Name  Age
2    C   30
3    D   35
  Name  Age
1    B   25
2    C   30
  Name  Age
0    A   20
2    C   30


## GroupBy

In [6]:
#Used for summarizing data.
import pandas as pd

df = pd.DataFrame({
    "Department":["IT","HR","IT","HR","Finance"],
    "Salary":[50000,40000,60000,45000,70000]
})

print(df.groupby("Department")["Salary"].mean())

print(df.groupby("Department")["Salary"].agg(["mean","max","min","sum"]))

Department
Finance    70000.0
HR         42500.0
IT         55000.0
Name: Salary, dtype: float64
               mean    max    min     sum
Department                               
Finance     70000.0  70000  70000   70000
HR          42500.0  45000  40000   85000
IT          55000.0  60000  50000  110000


## Missing Value Handling

In [7]:
#Real-world datasets often contain missing values.
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Name":["A","B","C","D"],
    "Age":[20,np.nan,30,np.nan]
})

print(df.isnull().sum())

df["Age"] = df["Age"].fillna(df["Age"].mean())
print(df)

print(df.dropna())

Name    0
Age     2
dtype: int64
  Name   Age
0    A  20.0
1    B  25.0
2    C  30.0
3    D  25.0
  Name   Age
0    A  20.0
1    B  25.0
2    C  30.0
3    D  25.0


## Data Preprocessing

In [8]:
#Data preprocessing prepares data for Machine Learning.
import pandas as pd

df = pd.DataFrame({
    "Name":["A","A","B","C"],
    "Age":[20,20,25,30]
})

print(df.drop_duplicates())

df.rename(columns={"Age":"Employee_Age"}, inplace=True)
print(df)

df["Employee_Age"] = df["Employee_Age"].astype(float)
print(df.dtypes)

  Name  Age
0    A   20
2    B   25
3    C   30
  Name  Employee_Age
0    A            20
1    A            20
2    B            25
3    C            30
Name             object
Employee_Age    float64
dtype: object


## Feature Engineering

In [ ]:
#Creating new useful columns from existing columns.
import pandas as pd

df = pd.DataFrame({
    "Math":[80,90,75],
    "Science":[85,95,70]
})

df["Total"] = df["Math"] + df["Science"]
df["Average"] = df["Total"] / 2

print(df)

   Math  Science  Total  Average
0    80       85    165     82.5
1    90       95    185     92.5
2    75       70    145     72.5


## Mini Project

In [10]:
import pandas as pd
import numpy as np

data = {
    "Name":["A","B","C","D","E"],
    "Department":["IT","HR","IT","Finance","HR"],
    "Salary":[50000,np.nan,60000,70000,45000],
    "Experience":[2,4,5,8,3]
}

df = pd.DataFrame(data)

df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

df["Salary_Per_Year"] = df["Salary"] / df["Experience"]

high_salary = df[df["Salary"] > 50000]

department_avg = df.groupby("Department")["Salary"].mean()

print(df)
print(high_salary)
print(department_avg)

  Name Department   Salary  Experience  Salary_Per_Year
0    A         IT  50000.0           2          25000.0
1    B         HR  56250.0           4          14062.5
2    C         IT  60000.0           5          12000.0
3    D    Finance  70000.0           8           8750.0
4    E         HR  45000.0           3          15000.0
  Name Department   Salary  Experience  Salary_Per_Year
1    B         HR  56250.0           4          14062.5
2    C         IT  60000.0           5          12000.0
3    D    Finance  70000.0           8           8750.0
Department
Finance    70000.0
HR         50625.0
IT         55000.0
Name: Salary, dtype: float64
