Transformers Overview

In [1]:
sentence = "I love Artificial Intelligence"
tokens = sentence.split()

print("Tokens:", tokens)
print("Number of Tokens:", len(tokens))

Tokens: ['I', 'love', 'Artificial', 'Intelligence']
Number of Tokens: 4


Tokens & Embeddings

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "I love AI",
    "AI is the future",
    "Machine Learning is part of AI"
]

vectorizer = CountVectorizer()
vectors = vectorizer.fit_transform(documents)

print(vectors.toarray())
print(vectorizer.get_feature_names_out())

[[1 0 0 0 1 0 0 0 0]
 [1 1 1 0 0 0 0 0 1]
 [1 0 1 1 0 1 1 1 0]]
['ai' 'future' 'is' 'learning' 'love' 'machine' 'of' 'part' 'the']


In [3]:
prompt = """
Act as a Python Trainer.

Explain List Comprehension with:
1. Definition
2. Syntax
3. Example
"""

print(prompt)


Act as a Python Trainer.

Explain List Comprehension with:
1. Definition
2. Syntax
3. Example



Vector Databases


In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

doc1 = np.array([[1, 2, 3]])
doc2 = np.array([[1, 2, 4]])

similarity = cosine_similarity(doc1, doc2)

print(similarity)